import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import 'package:printing/printing.dart';
import '../models/question_model.dart';
import '../models/mcq_model.dart';

class PdfGenerator {
  // Generate PDF for long/short questions
  static Future<File> generateQuestionsPdf({
    required List<Question> questions,
    required String title,
    bool includeAnswers = true,
  }) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: pw.EdgeInsets.all(32),
        build: (pw.Context context) {
          return [
            pw.Header(
              level: 0,
              child: pw.Text(
                title,
                style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold),
              ),
            ),
            pw.SizedBox(height: 20),
            
            ...questions.asMap().entries.map((entry) {
              final index = entry.key;
              final question = entry.value;
              
              return pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text(
                    'Q${index + 1}. ${question.question}',
                    style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
                  ),
                  pw.SizedBox(height: 10),
                  
                  if (includeAnswers) ...[
                    pw.Text('Answer:', style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold, color: PdfColors.blue900)),
                    pw.SizedBox(height: 5),
                    pw.Text(question.answer, style: pw.TextStyle(fontSize: 12), textAlign: pw.TextAlign.justify),
                  ] else ...[
                    pw.Container(height: 100, decoration: pw.BoxDecoration(border: pw.Border.all(color: PdfColors.grey300))),
                  ],
                  
                  pw.SizedBox(height: 20),
                  pw.Divider(),
                  pw.SizedBox(height: 20),
                ],
              );
            }).toList(),
            
            pw.SizedBox(height: 20),
            pw.Text('Generated by ExamCraft AI', style: pw.TextStyle(fontSize: 10, color: PdfColors.grey600), textAlign: pw.TextAlign.center),
          ];
        },
      ),
    );

    final output = await getApplicationDocumentsDirectory();
    final timestamp = DateTime.now().millisecondsSinceEpoch;
    final file = File('${output.path}/questions_$timestamp.pdf');
    await file.writeAsBytes(await pdf.save());
    
    return file;
  }

  // Generate PDF for MCQs
  static Future<File> generateMCQsPdf({
    required List<MCQ> mcqs,
    required String title,
    bool includeAnswers = true,
  }) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: pw.EdgeInsets.all(32),
        build: (pw.Context context) {
          return [
            pw.Header(
              level: 0,
              child: pw.Text(
                title,
                style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold),
              ),
            ),
            pw.SizedBox(height: 20),
            
            ...mcqs.asMap().entries.map((entry) {
              final index = entry.key;
              final mcq = entry.value;
              
              return pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text(
                    'Q${index + 1}. ${mcq.question}',
                    style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
                  ),
                  pw.SizedBox(height: 10),
                  
                  // Options
                  ...mcq.options.asMap().entries.map((optEntry) {
                    final optIndex = optEntry.key;
                    final option = optEntry.value;
                    final isCorrect = includeAnswers && optIndex == mcq.correctAnswerIndex;
                    
                    return pw.Padding(
                      padding: pw.EdgeInsets.only(left: 20, bottom: 5),
                      child: pw.Text(
                        '${String.fromCharCode(65 + optIndex)}. $option',
                        style: pw.TextStyle(
                          fontSize: 12,
                          fontWeight: isCorrect ? pw.FontWeight.bold : pw.FontWeight.normal,
                          color: isCorrect ? PdfColors.green700 : PdfColors.black,
                        ),
                      ),
                    );
                  }).toList(),
                  
                  if (includeAnswers) ...[
                    pw.SizedBox(height: 10),
                    pw.Container(
                      padding: pw.EdgeInsets.all(8),
                      decoration: pw.BoxDecoration(
                        color: PdfColors.green50,
                        borderRadius: pw.BorderRadius.circular(4),
                      ),
                      child: pw.Text(
                        'Correct Answer: ${mcq.correctAnswer}',
                        style: pw.TextStyle(fontSize: 11, fontWeight: pw.FontWeight.bold, color: PdfColors.green900),
                      ),
                    ),
                  ],
                  
                  pw.SizedBox(height: 20),
                  pw.Divider(),
                  pw.SizedBox(height: 20),
                ],
              );
            }).toList(),
            
            pw.SizedBox(height: 20),
            pw.Text('Generated by ExamCraft AI', style: pw.TextStyle(fontSize: 10, color: PdfColors.grey600), textAlign: pw.TextAlign.center),
          ];
        },
      ),
    );

    final output = await getApplicationDocumentsDirectory();
    final timestamp = DateTime.now().millisecondsSinceEpoch;
    final file = File('${output.path}/mcqs_$timestamp.pdf');
    await file.writeAsBytes(await pdf.save());
    
    return file;
  }

  static Future<void> sharePdf(File pdfFile) async {
    await Printing.sharePdf(
      bytes: await pdfFile.readAsBytes(),
      filename: pdfFile.path.split('/').last,
    );
  }

  static Future<void> printPdf(File pdfFile) async {
    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => await pdfFile.readAsBytes(),
    );
  }
}
